services:
    postgres:
        image: postgres:latest
        container_name: postgres
        restart: always
        environment:
            POSTGRES_DB: sentinal_db
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
        ports:
            - "5432:5432"
        volumes:
            - ./postgres-data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: coreystagnerllc@gmail.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        volumes:
            - ./pgadmin-data:/var/lib/pgadmin
        depends_on:
            - postgres